### ISSUE TITLE
The keyvault pkd cannot be handled by Golang packages.Load()

### ISSUE THREAD

**Issue by mybayern1974** [magodo/terraform-provider-azurerm-lro#1]
Error `Unexpected package creation during export data loading` was met:

I navigated reaching to this[ go func](https://github.com/golang/tools/blob/master/go/packages/packages.go#L632) that reported the above error, while I did yet figure out the root cause, i.e. which sub-pkg underneath the AzureRM keyvault package is incompatible with packages.Load()

**Comment by magodo** [comment]
Relating to: https://github.com/golang/go/issues/45218

I've tried with Go1.17, there is no problem:

```
terraform-provider-azurerm on  main via 🐹 v1.19.4 
💤  export PATH=/home/magodo/go1.17/go/bin:$PATH  

terraform-provider-azurerm on  main via 🐹 v1.17.3 
💤  terraform-provider-azurerm-lro ./internal/services/keyvault/...

terraform-provider-azurerm on  main via 🐹 v1.17.3 took 39s 
💤  echo $?
0
```

But the problem occurs with v1.19.4.
